'use strict';
const KEY='ascent_blueprint_v3_state', SNAP_KEY='ascent_blueprint_v3_backups', V2P='ascent_planner_v2', V2H='ascent_habits_v2';
const CATS=['همه','رشد فردی','سلامت','تمرکز','کار و یادگیری','سبک زندگی'];
const DAYS=['شنبه','یکشنبه','دوشنبه','سه‌شنبه','چهارشنبه','پنج‌شنبه','جمعه']; const SHORT=['ش','ی','د','س','چ','پ','ج'];
let state, selected=localISO(), activeCat='همه', saveTimer, undoAction, currentEditId=null;
const $=id=>document.getElementById(id); const clone=x=>JSON.parse(JSON.stringify(x));
function localISO(d=new Date()){const x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,10)}
function dateAt(iso){return new Date(iso+'T12:00:00')}; function shiftDate(iso,n){const d=dateAt(iso);d.setDate(d.getDate()+n);return localISO(d)}
function uid(){return crypto.randomUUID?crypto.randomUUID():'id-'+Date.now()+'-'+Math.random().toString(16).slice(2)}
function fa(n){return String(n).replace(/\d/g,d=>'۰۱۲۳۴۵۶۷۸۹'[d])} function en(n){return String(n).replace(/[۰-۹]/g,d=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(d))}
function toJalali(date){let gy=date.getFullYear()-1600,gm=date.getMonth()+1,gd=date.getDate()-1;const gdm=[31,28,31,30,31,30,31,31,30,31,30,31];let gday=365*gy+Math.floor((gy+3)/4)-Math.floor((gy+99)/100)+Math.floor((gy+399)/400);for(let i=0;i<gm-1;i++)gday+=gdm[i];if(gm>2&&((gy+1600)%4===0&&((gy+1600)%100!==0||(gy+1600)%400===0)))gday++;gday+=gd;let jday=gday-79,jnp=Math.floor(jday/12053);jday%=12053;let jy=979+33*jnp+4*Math.floor(jday/1461);jday%=1461;if(jday>=366){jy+=Math.floor((jday-1)/365);jday=(jday-1)%365}const jm=jday<186?1+Math.floor(jday/31):7+Math.floor((jday-186)/30);const jd=1+(jday<186?jday%31:(jday-186)%30);return[jy,jm,jd]}
function fromJalali(jy,jm,jd){if(!Number.isInteger(jy)||jm<1||jm>12||jd<1||jd>31)return null;let d=new Date(jy+621,2,15,12);for(let i=0;i<380;i++){const j=toJalali(d);if(j[0]===jy&&j[1]===jm&&j[2]===jd)return localISO(d);d.setDate(d.getDate()+1)}return null}
function jalaliText(iso){const [y,m,d]=toJalali(dateAt(iso));return `${fa(y)}/${fa(String(m).padStart(2,'0'))}/${fa(String(d).padStart(2,'0'))}`}
function weekday(iso){return DAYS[(dateAt(iso).getDay()+1)%7]}
function defaultSettings(){return{theme:'dark',highContrast:false,reducedMotion:false,planner:{start:'06:00',end:'22:00',interval:60}}}
function defaultDay(){return{priorities:[],goals:[],focus:[{id:uid(),label:'مطالعه',icon:'📖',text:'',completed:false},{id:uid(),label:'رشد فردی',icon:'↗',text:'',completed:false},{id:uid(),label:'تمرین',icon:'💪',text:'',completed:false}],schedule:[],lessons:'',reflection:{mood:3,score:0},weeklyReview:''}}
function defaultState(){return{schemaVersion:3,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),settings:defaultSettings(),planner:{days:{}},habits:{items:[]}}}
function normalize(raw){const s=raw&&typeof raw==='object'?raw:defaultState();s.schemaVersion=3;s.settings={...defaultSettings(),...(s.settings||{}),planner:{...defaultSettings().planner,...(s.settings?.planner||{})}};s.planner=s.planner||{days:{}};s.planner.days=s.planner.days||{};s.habits=s.habits||{items:[]};s.habits.items=Array.isArray(s.habits.items)?s.habits.items.filter(h=>h&&typeof h.name==='string').map(h=>{const history=h.history&&typeof h.history==='object'?h.history:{};return {...h,id:h.id||uid(),status:h.status||'active',category:h.category||'رشد فردی',icon:h.icon||'✦',history,startDate:h.startDate||Object.keys(history).sort()[0]||localISO(),goal:{type:'check',target:1,...(h.goal||{})},repeat:{mode:'daily',weekdays:[0,1,2,3,4,5,6],...(h.repeat||{})}}}):[];return s}
function load(){try{const raw=localStorage.getItem(KEY);state=normalize(raw?JSON.parse(raw):defaultState())}catch{state=defaultState();toast('بازیابی دادهٔ محلی ممکن نشد؛ وضعیت تازه ساخته شد.')}applySettings()}
function persist(immediate=false){$('saveState').textContent='در حال ذخیره…';$('saveState').className='save-state saving';clearTimeout(saveTimer);const save=()=>{try{state.updatedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(state));$('saveState').textContent='ذخیره شد';$('saveState').className='save-state'}catch(e){$('saveState').textContent='خطا در ذخیره؛ بکاپ بگیر';$('saveState').className='save-state error'}};if(immediate)save();else saveTimer=setTimeout(save,700)}
function day(iso=selected){if(!state.planner.days[iso])state.planner.days[iso]=defaultDay();const d=state.planner.days[iso];d.priorities=Array.isArray(d.priorities)?d.priorities:[];d.goals=Array.isArray(d.goals)?d.goals:[];d.focus=Array.isArray(d.focus)?d.focus:defaultDay().focus;d.schedule=Array.isArray(d.schedule)?d.schedule:[];d.reflection={mood:3,score:0,...(d.reflection||{})};return d}
function el(tag,props={},text){const x=document.createElement(tag);for(const[k,v]of Object.entries(props)){if(k==='class')x.className=v;else if(k.startsWith('on'))x.addEventListener(k.slice(2),v);else if(k==='dataset')Object.assign(x.dataset,v);else x.setAttribute(k,v)}if(text!==undefined)x.textContent=text;return x}
function input(value,props,onChange){const x=el('input',props);x.value=value||'';x.addEventListener('input',()=>{onChange(x.value);persist()});return x}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2600)}
function snapshot(label){try{let arr=[];try{arr=JSON.parse(localStorage.getItem(SNAP_KEY)||'[]')}catch{}arr.unshift({id:uid(),label,at:new Date().toISOString(),state:clone(state)});localStorage.setItem(SNAP_KEY,JSON.stringify(arr.slice(0,10)));return true}catch{toast('Snapshot ساخته نشد؛ فضای ذخیره‌سازی را بررسی کن.');return false}}
function undo(label,fn){undoAction=fn;$('undoText').textContent=label;$('undoBar').hidden=false;clearTimeout(undo.timer);undo.timer=setTimeout(()=>{$('undoBar').hidden=true;undoAction=null},30000)}
function score(d){const all=[...d.priorities,...d.goals,...d.focus,...d.schedule];const total=all.length,done=all.filter(x=>x.completed).length;return{total,done,pct:total?Math.round(done/total*100):0}}
function renderPlanner(){const d=day();const sc=score(d);$('heroDate').textContent=`${weekday(selected)} · ${jalaliText(selected)}`;$('jalaliDate').value=jalaliText(selected);$('dayScore').textContent=fa(sc.pct)+'٪';$('dayScoreMeta').textContent=`${fa(sc.done)} از ${fa(sc.total)} تکمیل`;
 renderItems('prioritiesList',d.priorities,'priority');renderItems('goalsList',d.goals,'goal');renderFocus(d);renderSchedule(d);$('lessonsInput').value=d.lessons||'';$('moodInput').value=d.reflection.mood;$('selfScoreInput').value=d.reflection.score;$('moodOutput').textContent=fa(d.reflection.mood)+'/۵';$('selfScoreOutput').textContent=fa(d.reflection.score)+'/۱۰'}
function renderItems(id,items,type){const root=$(id);root.replaceChildren();if(!items.length)root.append(el('p',{class:'empty'},type==='goal'?'هدفی اضافه نشده است.':'اولویتی اضافه نشده است.'));items.forEach((item,index)=>{const row=el('div',{class:'item-row '+(item.completed?'done':'')});const check=el('input',{class:'check',type:'checkbox','aria-label':`انجام ${item.text||type}`});check.checked=!!item.completed;check.addEventListener('change',()=>{item.completed=check.checked;persist(true);renderPlanner()});const text=input(item.text,{class:'item-text',placeholder:type==='goal'?'هدف امروز…':'کار مهم…','aria-label':type==='goal'?'هدف':'اولویت'},v=>item.text=v);const up=el('button',{class:'drag-handle',title:'جابه‌جایی به بالا',onclick:()=>move(items,index,-1)},'↑');const del=el('button',{class:'row-delete',title:'حذف',onclick:()=>removeArray(items,index,`حذف ${type}`)},'×');row.append(check,text,up,del);root.append(row)})}
function renderFocus(d){const root=$('focusList');root.replaceChildren();d.focus.forEach(f=>{const row=el('label',{class:'focus-row'}),check=el('input',{class:'check',type:'checkbox','aria-label':`انجام ${f.label}`});check.checked=!!f.completed;check.addEventListener('change',()=>{f.completed=check.checked;persist(true);renderPlanner()});row.append(check,el('span',{},`${f.icon} ${f.label}`),input(f.text,{class:'focus-input',placeholder:'جزئیات…'},v=>f.text=v));root.append(row)})}
function renderSchedule(d){const root=$('scheduleList');root.replaceChildren();if(!d.schedule.length)root.append(el('p',{class:'empty'},'هنوز بازه‌ای ایجاد نشده است. «تولید بازه» را بزن.'));d.schedule.forEach((b,i)=>{const row=el('div',{class:'schedule-row '+(b.completed?'done':'')});const check=el('input',{class:'check',type:'checkbox','aria-label':`تکمیل بلوک ${i+1}`});check.checked=!!b.completed;check.addEventListener('change',()=>{b.completed=check.checked;persist(true);renderPlanner()});const start=input(b.start,{class:'schedule-time',type:'time','aria-label':`شروع بلوک ${i+1}`},v=>{b.start=v;validateSchedule(d)});const end=input(b.end,{class:'schedule-time',type:'time','aria-label':`پایان بلوک ${i+1}`},v=>{b.end=v;validateSchedule(d)});const text=input(b.text,{class:'schedule-text',placeholder:'فعالیت…','aria-label':`فعالیت بلوک ${i+1}`},v=>b.text=v);const del=el('button',{class:'block-delete',title:'حذف بلوک',onclick:()=>removeArray(d.schedule,i,'حذف بلوک زمان')},'×');row.append(check,start,end,text,del);root.append(row)})}
function move(arr,i,delta){const j=i+delta;if(j<0||j>=arr.length)return;[arr[i],arr[j]]=[arr[j],arr[i]];persist(true);renderPlanner()}
function removeArray(arr,i,label){snapshot(label);const old=arr.splice(i,1)[0];persist(true);renderPlanner();undo(`${label} قابل بازگردانی است`,()=>{arr.splice(i,0,old);persist(true);renderPlanner()})}
function addPlanner(type){const d=day();if(type==='priority')d.priorities.push({id:uid(),text:'',completed:false});if(type==='goal')d.goals.push({id:uid(),text:'',completed:false});persist(true);renderPlanner()}
function validateSchedule(d){for(let i=0;i<d.schedule.length;i++){const b=d.schedule[i];b.invalid=!!(b.start&&b.end&&b.start>=b.end)}persist()}
function generateSchedule(){snapshot('تولید زمان‌بندی');const d=day(),s=state.settings.planner;const [sh,sm]=s.start.split(':').map(Number),[eh,em]=s.end.split(':').map(Number);let a=sh*60+sm,end=eh*60+em;d.schedule=[];while(a<end){const z=Math.min(a+Number(s.interval),end),fmt=n=>String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0');d.schedule.push({id:uid(),start:fmt(a),end:fmt(z),text:'',completed:false});a=z}persist(true);renderPlanner();toast('بازه‌های زمانی ساخته شدند')}
function resetDay(){snapshot('ریست روز');const old=clone(day());state.planner.days[selected]=defaultDay();persist(true);renderPlanner();undo('برنامهٔ این روز ریست شد',()=>{state.planner.days[selected]=old;persist(true);renderPlanner()})}
function copyPrev(){const prev=shiftDate(selected,-1);if(!state.planner.days[prev])return toast('برای روز قبل برنامه‌ای وجود ندارد.');snapshot('کپی روز قبل');state.planner.days[selected]=clone(state.planner.days[prev]);state.planner.days[selected].schedule.forEach(x=>x.completed=false);[...state.planner.days[selected].priorities,...state.planner.days[selected].goals,...state.planner.days[selected].focus].forEach(x=>x.completed=false);persist(true);renderPlanner();toast('برنامهٔ روز قبل کپی شد')}
const templates={کاری:{priorities:['مهم‌ترین خروجی امروز','کار عمیق','پیگیری ضروری'],goals:['یک خروجی قابل تحویل'],blocks:['ایمیل و برنامه‌ریزی','تمرکز عمیق','جلسه/همکاری','جمع‌بندی']},دانشجو:{priorities:['مطالعهٔ عمیق','حل تمرین','مرور'],goals:['تکمیل یک مبحث'],blocks:['مطالعه','استراحت','حل تمرین','مرور']},تمرکز:{priorities:['یک کار حیاتی'],goals:['۴ ساعت بدون حواس‌پرتی'],blocks:['تمرکز عمیق','استراحت','تمرکز عمیق','مرور']},خالی:{priorities:[],goals:[],blocks:[]}};
function showTemplates(){const root=$('templatesList');root.replaceChildren();Object.entries(templates).forEach(([name,t])=>{const b=el('button',{class:'template',type:'button',onclick:()=>applyTemplate(name)});b.append(el('b',{},name),el('small',{},`${t.priorities.length} اولویت · ${t.blocks.length} بلوک`));root.append(b)});$('templateDialog').showModal()}
function applyTemplate(name){snapshot('اعمال قالب '+name);const t=templates[name],d=day();d.priorities=t.priorities.map(text=>({id:uid(),text,completed:false}));d.goals=t.goals.map(text=>({id:uid(),text,completed:false}));d.schedule=t.blocks.map((text,i)=>({id:uid(),start:String(8+i*2).padStart(2,'0')+':00',end:String(10+i*2).padStart(2,'0')+':00',text,completed:false}));persist(true);$('templateDialog').close();renderPlanner();toast(`قالب «${name}» اعمال شد`)}
function due(h,iso=localISO()){if(h.startDate&&iso<h.startDate)return false;const w=(dateAt(iso).getDay()+1)%7;return h.repeat.mode==='daily'||h.repeat.weekdays.includes(w)}
function valFor(h,iso){return Number(h.history?.[iso]?.value||0)} function completed(h,iso=localISO()){return due(h,iso)&&valFor(h,iso)>=Number(h.goal.target||1)}
function previousDueDate(h,from){let d=from;for(let i=0;i<370;i++,d=shiftDate(d,-1))if(due(h,d))return d;return null}
function currentStreak(h){let n=0,d=previousDueDate(h,localISO());while(d&&completed(h,d)){n++;d=previousDueDate(h,shiftDate(d,-1))}return n}
function longestStreak(h){let n=0,best=0,d=shiftDate(localISO(),-365);for(let i=0;i<366;i++,d=shiftDate(d,1)){if(!due(h,d))continue;if(completed(h,d)){n++;best=Math.max(best,n)}else n=0}return best}
function activeHabits(){return state.habits.items.filter(h=>h.status==='active')}
function setHabitValue(h,value,iso=localISO(),rerender=true){const target=Math.max(1,Number(h.goal.target)||1);const normalized=Math.max(0,Math.min(999999,Number(value)||0));h.history[iso]={value:normalized,updatedAt:new Date().toISOString()};persist(true);if(rerender)renderHabits();return {value:normalized,target,completed:normalized>=target}}
function renderHabits(){const today=localISO(),all=activeHabits(),dueToday=all.filter(h=>due(h,today)),done=dueToday.filter(h=>completed(h,today));$('habitDate').textContent=`${weekday(today)} · ${jalaliText(today)}`;const rate=dueToday.length?Math.round(done.length/dueToday.length*100):0;$('habitRate').textContent=fa(rate)+'٪';$('habitRateMeta').textContent=`${fa(done.length)} از ${fa(dueToday.length)} عادت`;$('progressRing').style.setProperty('--progress',rate+'%');$('habitTotal').textContent=fa(all.length);const currents=all.map(currentStreak),longs=all.map(longestStreak);$('currentStreak').textContent=fa(Math.max(0,...currents));$('longestStreak').textContent=fa(Math.max(0,...longs));let wd=0,wt=0;for(let i=0;i<7;i++){const dt=shiftDate(today,-i);all.forEach(h=>{if(due(h,dt)){wt++;if(completed(h,dt))wd++}})}$('weekRate').textContent=fa(wt?Math.round(wd/wt*100):0)+'٪';renderFilters();let shown=all.filter(h=>activeCat==='همه'||h.category===activeCat);const sort=$('habitSort').value;shown.sort((a,b)=>sort==='streak'?currentStreak(b)-currentStreak(a):sort==='rate'?habitRate(b)-habitRate(a):sort==='name'?a.name.localeCompare(b.name,'fa'):0);const root=$('habitsList');root.replaceChildren();if(!shown.length)root.append(el('p',{class:'empty'},all.length?'در این دسته عادتی وجود ندارد.':'اولین عادت کوچک را بساز.'));shown.forEach(h=>root.append(habitRow(h,today)));$('habitCountLabel').textContent=`${fa(shown.length)} عادت`;renderWeek(all,today);renderHeat(all,today);renderInsights(all,today)}
function habitRate(h){let a=0,b=0;for(let i=0;i<30;i++){let d=shiftDate(localISO(),-i);if(due(h,d)){b++;if(completed(h,d))a++}}return b?a/b:0}
function habitRow(h,today){const done=completed(h,today),row=el('article',{class:'habit-row '+(done?'completed':'')});const main=el('div',{class:'habit-main'});main.append(el('span',{class:'habit-name'},`${h.icon} ${h.name}`),el('small',{class:'habit-meta'},`${h.category} · فعلی ${fa(currentStreak(h))} روز · رکورد ${fa(longestStreak(h))} روز`));let leading,control;if(h.goal.type==='check'){leading=el('input',{class:'check',type:'checkbox','aria-label':`ثبت ${h.name}`});leading.checked=done;leading.addEventListener('change',()=>setHabitValue(h,leading.checked?1:0));control=el('span',{class:'tag'},done?'انجام شد':'امروز')}else{leading=el('span',{class:'goal-icon',title:h.goal.type==='duration'?'هدف زمانی':'هدف تعدادی'},h.goal.type==='duration'?'◷':'#');const unit=h.goal.type==='duration'?'دقیقه':'بار';control=el('div',{class:'habit-stepper','aria-label':`پیشرفت ${h.name}`});const minus=el('button',{type:'button',title:'کم کردن یک واحد','aria-label':`کاهش ${h.name}`,onclick:()=>setHabitValue(h,valFor(h,today)-1)} ,'−');const progress=el('span',{class:'habit-progress'},`${fa(valFor(h,today))}/${fa(h.goal.target)} ${unit}`);const plus=el('button',{type:'button',title:'افزودن یک واحد','aria-label':`افزودن به ${h.name}`,onclick:()=>setHabitValue(h,valFor(h,today)+1)},'+');const inp=el('input',{type:'number',min:'0','aria-label':`مقدار ${h.name}`});inp.value=valFor(h,today);inp.addEventListener('change',()=>setHabitValue(h,inp.value));control.append(minus,inp,progress,plus)}const edit=el('button',{class:'habit-edit',title:'ویرایش عادت',onclick:()=>openHabit(h)},'ویرایش');row.append(leading,main,control,edit);return row}
function renderFilters(){const r=$('categoryFilters');r.replaceChildren();CATS.forEach(c=>{const b=el('button',{class:'filter '+(activeCat===c?'active':''),onclick:()=>{activeCat=c;renderHabits()}},c);r.append(b)})}
function renderWeek(all,today){const r=$('weeklyChart');r.replaceChildren();for(let i=6;i>=0;i--){const d=shiftDate(today,-i),dueHs=all.filter(h=>due(h,d)),pct=dueHs.length?dueHs.filter(h=>completed(h,d)).length/dueHs.length:0,level=pct?Math.ceil(pct*4):0,cell=el('div',{class:'week-cell l'+level,title:`${jalaliText(d)}: ${Math.round(pct*100)}٪`});cell.append(el('span',{},SHORT[(dateAt(d).getDay()+1)%7]),el('b',{},fa(Math.round(pct*100))+'٪'));r.append(cell)}const best=all.sort((a,b)=>currentStreak(b)-currentStreak(a))[0];$('habitInsight').textContent=best&&currentStreak(best)?`🔥 «${best.name}» با ${fa(currentStreak(best))} روز، بهترین استریک فعال توست.`:'امروز بهترین فرصت برای ساختن اولین استریک است.'}
function renderHeat(all,today){const r=$('heatmap');r.replaceChildren();for(let i=29;i>=0;i--){const d=shiftDate(today,-i),dueHs=all.filter(h=>due(h,d)),pct=dueHs.length?dueHs.filter(h=>completed(h,d)).length/dueHs.length:0;const c=el('button',{class:'heat-cell l'+(pct?Math.ceil(pct*4):0)+(d===today?' today':''),title:`${jalaliText(d)} · ${Math.round(pct*100)}٪`,type:'button',onclick:()=>openHistory(d)});r.append(c)}}
function renderInsights(all,today){const root=$('insightCards');root.replaceChildren();let bestDay={name:'—',rate:-1};for(let w=0;w<7;w++){let a=0,b=0;for(let i=0;i<70;i++){const d=shiftDate(today,-i);if((dateAt(d).getDay()+1)%7!==w)continue;all.forEach(h=>{if(due(h,d)){b++;if(completed(h,d))a++}})}if(b&&a/b>bestDay.rate)bestDay={name:DAYS[w],rate:a/b}}const weak=all.slice().sort((a,b)=>habitRate(a)-habitRate(b))[0],hero=all.slice().sort((a,b)=>longestStreak(b)-longestStreak(a))[0];const cards=[['بهترین روز هفته',bestDay.rate>=0?bestDay.name:'داده کافی نیست',bestDay.rate>=0?`${fa(Math.round(bestDay.rate*100))}٪ نرخ تکمیل؛ کار سخت را در این روز برنامه‌ریزی کن.`:'برای ساخت این تحلیل، چند روز عادت‌ها را ثبت کن.'],['عادت نیازمند توجه',weak?weak.name:'—',weak?`نرخ ۳۰ روزه: ${fa(Math.round(habitRate(weak)*100))}٪. هدف را کوچک‌تر یا زمان آن را مشخص‌تر کن.`:'هنوز عادتی ساخته نشده است.'],['قوی‌ترین پیوستگی',hero?hero.name:'—',hero?`رکورد تاریخی: ${fa(longestStreak(hero))} روز. از این الگو برای عادت‌های دیگر الهام بگیر.`:'با یک عادت ساده شروع کن.']];cards.forEach(([s,b,p])=>{const c=el('article',{class:'panel insight-card'});c.append(el('span',{},s),el('b',{},b),el('p',{},p));root.append(c)});$('weeklyReview').value=state.planner.days[selected]?.weeklyReview||''}
function updateGoalInput(){const simple=$('habitGoalType').value==='check';$('habitTarget').disabled=simple;$('habitTarget').closest('label').style.opacity=simple?'0.55':'1';if(simple)$('habitTarget').value=1}
function openHabit(h=null){currentEditId=h?.id||null;$('habitDialogTitle').textContent=h?'ویرایش عادت':'عادت جدید';$('habitId').value=h?.id||'';$('archiveHabitBtn').hidden=!h;$('deleteHabitBtn').hidden=!h;$('habitName').value=h?.name||'';$('habitCategory').value=h?.category||'رشد فردی';$('habitIcon').value=h?.icon||'✦';$('habitGoalType').value=h?.goal?.type||'check';$('habitTarget').value=h?.goal?.target||1;updateGoalInput();$('habitNotes').value=h?.notes||'';renderRepeat(h?.repeat?.weekdays||[0,1,2,3,4,5,6]);$('habitDialog').showModal()}
function renderRepeat(selectedDays){const r=$('repeatDays');r.replaceChildren();DAYS.forEach((name,i)=>{const l=el('label'),x=el('input',{type:'checkbox',value:i});x.checked=selectedDays.includes(i);l.append(x,el('span',{},name));r.append(l)})}
function saveHabit(){const name=$('habitName').value.trim();if(!name)return toast('نام عادت را وارد کن.');const weekdays=[...document.querySelectorAll('#repeatDays input:checked')].map(x=>Number(x.value));if(!weekdays.length)return toast('حداقل یک روز تکرار انتخاب کن.');const id=$('habitId').value,h=state.habits.items.find(x=>x.id===id);const goalType=$('habitGoalType').value;const data={name,category:$('habitCategory').value,icon:$('habitIcon').value.trim()||'✦',notes:$('habitNotes').value.trim(),goal:{type:goalType,target:goalType==='check'?1:Math.max(1,Number($('habitTarget').value)||1)},repeat:{mode:weekdays.length===7?'daily':'weekly',weekdays}};if(h)Object.assign(h,data);else state.habits.items.push({id:uid(),status:'active',startDate:localISO(),history:{},...data});persist(true);$('habitDialog').close();renderHabits();toast('عادت ذخیره شد')}
function archiveCurrentHabit(){const h=state.habits.items.find(x=>x.id===currentEditId);if(!h)return;if(!confirm(`«${h.name}» آرشیو شود؟`))return;snapshot('آرشیو عادت');h.status='archived';h.archivedAt=new Date().toISOString();persist(true);$('habitDialog').close();renderHabits();undo('عادت آرشیو شد',()=>{h.status='active';h.archivedAt=null;persist(true);renderHabits()})}
function deleteCurrentHabit(){const i=state.habits.items.findIndex(x=>x.id===currentEditId);if(i<0||!confirm('این عادت و تاریخچه‌اش حذف شود؟'))return;snapshot('حذف عادت');const h=state.habits.items.splice(i,1)[0];persist(true);$('habitDialog').close();renderHabits();undo('عادت حذف شد',()=>{state.habits.items.splice(i,0,h);persist(true);renderHabits()})}
function openHistory(iso){const all=activeHabits();if(!all.length)return toast('ابتدا یک عادت اضافه کن.');$('historyDate').value=iso;$('historyDateLabel').textContent=`ثبت تاریخچه برای ${jalaliText(iso)}`;const select=$('historyHabit');select.replaceChildren();all.forEach(h=>select.append(el('option',{value:h.id},h.name)));const fill=()=>{const h=all.find(x=>x.id===select.value);$('historyValue').value=valFor(h,iso)};select.onchange=fill;fill();$('historyDialog').showModal()}
function saveHistory(){const iso=$('historyDate').value,h=state.habits.items.find(x=>x.id===$('historyHabit').value);if(!h)return;if(iso>localISO())return toast('برای تاریخ آینده نمی‌توان ثبت کرد.');setHabitValue(h,$('historyValue').value,iso);$('historyDialog').close();toast('تاریخچه به‌روزرسانی شد')}
function exportJson(){download('ascent-blueprint-v3-backup-'+localISO()+'.json',JSON.stringify({app:'Ascent Blueprint',version:3,exportedAt:new Date().toISOString(),state},null,2),'application/json');toast('بکاپ JSON دانلود شد')}
function exportCsv(){const rows=[['type','date','name','value','completed']];Object.entries(state.planner.days).forEach(([date,d])=>rows.push(['planner',date,'lessons',JSON.stringify(d.lessons||''),'']));state.habits.items.forEach(h=>Object.entries(h.history).forEach(([date,v])=>rows.push(['habit',date,h.name,v.value,Number(Number(v.value)>=h.goal.target)])));download('ascent-blueprint-v3-'+localISO()+'.csv',rows.map(r=>r.map(x=>'"'+String(x??'').replace(/"/g,'""')+'"').join(',')).join('\n'),'text/csv;charset=utf-8');toast('خروجی CSV دانلود شد')}
function download(name,data,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function importFile(file){if(!file)return;if(file.size>5*1024*1024)return toast('حجم فایل بکاپ بیش از حد مجاز است.');const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result),candidate=normalize(data.state||data);if(!confirm('دادهٔ فعلی با بکاپ جایگزین شود؟ ابتدا یک Snapshot ساخته می‌شود.'))return;snapshot('پیش از ورود بکاپ');state=candidate;persist(true);applySettings();renderAll();$('settingsDialog').close();toast('بکاپ با موفقیت بازیابی شد')}catch{toast('فایل بکاپ معتبر نیست.')}};reader.readAsText(file)}
function renderSnapshots(){let arr=[];try{arr=JSON.parse(localStorage.getItem(SNAP_KEY)||'[]')}catch{}const r=$('snapshotsList');r.replaceChildren();if(!arr.length)r.append(el('small',{},'هنوز Snapshotی وجود ندارد.'));arr.forEach(s=>{const row=el('div',{class:'snapshot'});const b=el('button',{class:'mini-btn',onclick:()=>{if(confirm('این Snapshot جایگزین دادهٔ فعلی شود؟')){snapshot('پیش از بازیابی Snapshot');state=normalize(s.state);persist(true);renderAll();toast('Snapshot بازیابی شد')}}},'بازیابی');row.append(el('span',{},`${s.label} · ${new Date(s.at).toLocaleString('fa-IR')}`),b);r.append(row)})}
function applySettings(){const s=state.settings;document.body.classList.toggle('light',s.theme==='light');document.body.classList.toggle('high-contrast',!!s.highContrast);document.body.classList.toggle('reduced-motion',!!s.reducedMotion)}
function settingsOpen(){const s=state.settings;$('startHour').value=s.planner.start;$('endHour').value=s.planner.end;$('interval').value=s.planner.interval;$('lightTheme').checked=s.theme==='light';$('highContrast').checked=!!s.highContrast;$('reducedMotion').checked=!!s.reducedMotion;renderSnapshots();$('settingsDialog').showModal()}
function saveSettings(){state.settings={...state.settings,theme:$('lightTheme').checked?'light':'dark',highContrast:$('highContrast').checked,reducedMotion:$('reducedMotion').checked,planner:{start:$('startHour').value,end:$('endHour').value,interval:Number($('interval').value)}};persist(true);applySettings();$('settingsDialog').close();toast('تنظیمات ذخیره شد')}
function switchView(view){['planner','habits','insights'].forEach(v=>{$(v+'View').hidden=v!==view;document.querySelector(`[data-view="${v}"]`).classList.toggle('active',v===view);document.querySelector(`[data-view="${v}"]`).setAttribute('aria-selected',String(v===view))});if(view==='habits')renderHabits();if(view==='insights')renderInsights(activeHabits(),localISO())}
function migrateV2Offer(){if(localStorage.getItem(KEY)||!localStorage.getItem(V2P))return;try{if(!confirm('دادهٔ نسخهٔ ۲ پیدا شد. آیا می‌خواهی یک کپی از آن به نسخهٔ ۳ وارد شود؟'))return;const p=JSON.parse(localStorage.getItem(V2P)||'{}'),h=JSON.parse(localStorage.getItem(V2H)||'{}');Object.entries(p.records||{}).forEach(([date,x])=>{state.planner.days[date]={priorities:(x.priorities||[]).map(a=>({id:uid(),text:a.text||'',completed:!!a.checked})),goals:(x.goals||[]).map(text=>({id:uid(),text,completed:false})),focus:[{id:uid(),label:'مطالعه',icon:'📖',text:x.studyText||'',completed:!!x.studyChecked},{id:uid(),label:'رشد فردی',icon:'↗',text:x.growthText||'',completed:!!x.growthChecked},{id:uid(),label:'تمرین',icon:'💪',text:x.exerciseText||'',completed:!!x.exerciseChecked}],schedule:(x.schedule||[]).map(b=>({id:uid(),start:b.time||'',end:'',text:b.activity||'',completed:false})),lessons:x.lessons||'',reflection:{mood:3,score:0},weeklyReview:''}});state.habits.items=(h.items||[]).map(x=>({id:uid(),name:x.name,icon:'✦',category:x.category||'رشد فردی',status:'active',notes:'',goal:{type:'check',target:1},repeat:{mode:'daily',weekdays:[0,1,2,3,4,5,6]},history:Object.fromEntries(Object.entries(x.history||{}).map(([d,v])=>[d,{value:v?1:0}]))}));persist(true);toast('دادهٔ V2 کپی شد؛ فایل و دادهٔ V2 دست‌نخورده‌اند.')}catch{toast('مهاجرت V2 انجام نشد؛ دادهٔ اصلی محفوظ است.')}}
function renderAll(){renderPlanner();renderHabits();renderInsights(activeHabits(),localISO())}
function bind(){document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('prevDay').onclick=()=>{selected=shiftDate(selected,-1);renderPlanner()};$('nextDay').onclick=()=>{selected=shiftDate(selected,1);renderPlanner()};$('todayBtn').onclick=()=>{selected=localISO();renderPlanner()};$('jalaliDate').addEventListener('change',()=>{const a=en($('jalaliDate').value).trim().split(/[/-]/).map(Number),iso=fromJalali(...a);if(iso){selected=iso;renderPlanner()}else{toast('تاریخ شمسی معتبر نیست.');renderPlanner()}});document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addPlanner(b.dataset.add));$('addBlockBtn').onclick=()=>{day().schedule.push({id:uid(),start:'',end:'',text:'',completed:false});persist(true);renderPlanner()};$('generateScheduleBtn').onclick=generateSchedule;$('resetDayBtn').onclick=()=>{if(confirm(`برنامهٔ ${jalaliText(selected)} ریست شود؟`))resetDay()};$('copyPrevBtn').onclick=copyPrev;$('templateBtn').onclick=showTemplates;$('printBtn').onclick=()=>window.print();$('lessonsInput').oninput=e=>{day().lessons=e.target.value;persist()};$('moodInput').oninput=e=>{day().reflection.mood=Number(e.target.value);$('moodOutput').textContent=fa(e.target.value)+'/۵';persist()};$('selfScoreInput').oninput=e=>{day().reflection.score=Number(e.target.value);$('selfScoreOutput').textContent=fa(e.target.value)+'/۱۰';persist()};$('addHabitBtn').onclick=()=>openHabit();$('habitSort').onchange=renderHabits;$('habitGoalType').onchange=updateGoalInput;$('habitForm').addEventListener('submit',e=>{e.preventDefault();saveHabit()});$('archiveHabitBtn').onclick=archiveCurrentHabit;$('deleteHabitBtn').onclick=deleteCurrentHabit;$('historyForm').addEventListener('submit',e=>{e.preventDefault();saveHistory()});$('settingsBtn').onclick=settingsOpen;$('settingsForm').addEventListener('submit',e=>{e.preventDefault();saveSettings()});$('exportJsonBtn').onclick=exportJson;$('exportCsvBtn').onclick=exportCsv;$('importFile').onchange=e=>importFile(e.target.files[0]);document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());$('undoBtn').onclick=()=>{if(undoAction){undoAction();$('undoBar').hidden=true;undoAction=null;toast('بازگردانی انجام شد')}};$('weeklyReview').oninput=e=>{day().weeklyReview=e.target.value;persist()};document.addEventListener('keydown',e=>{if(e.altKey&&e.key==='ArrowRight')switchView('planner');if(e.altKey&&e.key==='ArrowLeft')switchView('habits')})}
load();migrateV2Offer();bind();renderAll();if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('service-worker.js').catch(()=>{});
